[diagnostics]
enabled = false
sql_linter = true

[package_management]
manager = "uv"

[ai]
mode = "manual"
rules = ""
inline_tooltip = false

[ai.anthropic]

[ai.bedrock]

[ai.google]

[ai.models]
displayed_models = []
custom_models = []

[ai.open_ai]

[keymap]
preset = "vim"
destructive_delete = true

[keymap.overrides]

[mcp]
presets = []

[mcp.mcpServers]

[display]
cell_output = "below"
code_editor_font_size = 14
default_table_page_size = 25
theme = "light"
reference_highlighting = true
dataframes = "rich"
default_table_max_columns = 50
default_width = "full"

[completion]
activate_on_typing = true
copilot = "github"

[snippets]
include_default_snippets = true
custom_paths = []

[experimental]
external_agents = true
multi_column = true
tracing = true
chat_sidebar = true

[save]
autosave_delay = 1000
autosave = "after_delay"
format_on_save = true

[formatting]
line_length = 79

[language_servers.ty]
enabled = true

[language_servers.pylsp]
enabled = false
enable_ruff = false
enable_pyflakes = false
enable_mypy = false
enable_pydocstyle = false
enable_pylint = false
enable_flake8 = false

[language_servers.basedpyright]

[runtime]
watcher_on_save = "lazy"
auto_instantiate = true
default_auto_download = []
default_sql_output = "auto"
dotenv = []
on_cell_change = "autorun"
reactive_tests = true
auto_reload = "autorun"
output_max_bytes = 8000000
std_stream_max_bytes = 1000000

[server]
browser = "default"
follow_symlink = false
