# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
gui:
  border: 'rounded'
  nerdFontsVersion: "3"
git:
  overrideGpg: true
  pagers:
    - colorArg: 'always'
      pager: >
        diff-so-fancy

keybinding:
  commits:
    moveDownCommit: 'J'
    moveUpCommit: 'K'
