# Inside the repository
# Given project `./myproject` and branch `my-feature`
# Creates: `./myproject/.worktrees/my-feature`
worktree-path = ".worktrees/{{ branch | sanitize }}"

[projects."github.com/baggiponte/sklab"]
approved-commands = [
    "uv sync",
]

[projects."biosphere.teamsystem.com/tsdigital/oneplatform/machine-learning/ai-platform-core"]
approved-commands = [
    "uv venv --python=3.11",
    "poetry install --with=dev",
]
